---
- hosts: web
  gather_facts: false

  tasks:
    - name: Update the code
      git:
        repo: https://github.com/opdavies/oliverdavies.uk
        dest: ~/oliverdavies.uk

    - name: Pull the latest images and re-generate the site.
      shell: ./run run-production
      args:
        chdir: ~/oliverdavies.uk
