---
- hosts: web

  tasks:
    - name: Pull the latest images and restart the services
      shell: |
        docker-compose --file docker-compose-production.yaml pull
        docker-compose --file docker-compose-production.yaml up --detach
      args:
        chdir: oliverdavies.uk
