---
- hosts: web
  gather_facts: false

  tasks:
    - name: Pull the latest images and re-generate the site.
      shell: |
        git pull
        docker-compose up --detach
      args:
        chdir: /var/www/oliverdavies.uk
