name: oliverdavies-uk
type: sculpin
language: php

flake:
  devshell:
    packages:
      - nodePackages.pnpm
      - nodejs
      - php81
      - php81Packages.composer

git:
  ignore:
    - '/source/build/'
    - '/node_modules/'

experimental:
  createTmuxStartupFile: true
