name: oliverdavies-uk
type: sculpin
language: php

flake:
  devshell:
    packages:
      - bashInteractive
      - nodePackages.pnpm
      - nodejs
      - php82
      - php82Packages.composer

git:
  ignore:
    - '/.phpunit.cache/'
    - '/assets/node_modules/'
    - '/source/build/'
