name: oliverdavies-uk
type: sculpin
language: php

flake:
  devshell:
    packages:
      - ansible
      - nodePackages.pnpm
      - nodejs
      - php82
      - php82Packages.composer

git:
  ignore:
    - '/source/build/'
    - '/node_modules/'
