name: oliverdavies-uk
type: sculpin
language: php

flake:
  devshell:
    packages:
      - nodePackages.pnpm
      - nodejs
      - php81
      - php81Packages.composer

git:
  ignore:
    - '/source/build/'
    - '!/assets/'
    - '!/data/'
    - '!/package.json'
    - '!/pnpm-lock.yaml'
    - '!/stub.md'

experimental:
  createInclusiveGitIgnoreFile: true
  createTmuxStartupFile: true
