services:
  app:
    build:
      context: .
      target: build
    image: "ghcr.io/opdavies/oliverdavies.uk-web:${DOCKER_TAG:-latest}"
    command: "sculpin generate --clean --port ${SCULPIN_PORT:-8000} --url ${SCULPIN_URL:-http://localhost} --env ${SCULPIN_ENV:-dev} ${SCULPIN_GENERATE_ARGS}"
    volumes:
      - .:/app
    ports:
      - "${DOCKER_COMPOSE_WEB_FORWARD:-127.0.0.1:80}:8000"
    env_file:
      - .env
    tty: true
