version: '2.4'

services:
  app:
    image: opdavies/sculpin-serve
    volumes:
      - assets:/app/source/build
      - /app/output_dev
      - .:/app
    ports:
      - 8000:8000

  assets:
    build:
      context: .
      dockerfile: tools/docker/images/node/Dockerfile
    volumes:
      - assets:/node/source/build
      - /node/node_modules
      - ./assets:/node/assets
      - ./package.json:/node/package.json
      - ./package-lock.json:/node/package-lock.json
      - ./postcss.config.js:/node/postcss.config.js
      - ./source:/node/source
      - ./tailwind.config.js:/node/tailwind.config.js
      - ./tools/tailwindcss:/node/tools/tailwindcss
      - ./webpack.config.js:/node/webpack.config.js
    entrypoint: npm
    command: run watch

volumes:
  assets:
