services:
  app:
    build:
      context: .
      target: build
    image: "ghcr.io/opdavies/oliverdavies.uk-web:${DOCKER_TAG:-latest}"
    command: "sculpin generate --clean --no-interaction --url ${SCULPIN_URL:-http://localhost} --env ${SCULPIN_ENV:-dev} ${SCULPIN_GENERATE_ARGS}"
    volumes:
      - .:/app
    tty: true
    expose:
      - 8000
    networks:
      - web
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.oliverdavies.rule=Host(`oliverdavies.docker.localhost`)"

networks:
  web:
    external:
      name: traefik_proxy
