services:
  app:
    build:
      context: .
      target: build
    command: sculpin generate --clean --port "${SCULPIN_PORT:-80}" --url "${SCULPIN_URL:-http://localhost}" --env "${SCULPIN_ENV:-dev}" "${SCULPIN_GENERATE_ARGS}" --output-dir output --no-interaction
    volumes:
      - .:/app
    ports:
      - "${SCULPIN_PORT:-80}:${SCULPIN_PORT:-80}"
    env_file:
      - .env
    tty: true
