version: '2.4'

services:
  web:
    build:
      context: .
      dockerfile: tools/docker/images/Dockerfile
      target: production
    image: "ghcr.io/opdavies/oliverdavies-uk-web:${DOCKER_TAG:-latest}"
    ports:
      - 80:8080
    restart: unless-stopped
