source 'https://rubygems.org'

group :development do

  gem "sass", "3.3.9"
	gem "sass-globbing", "1.1.1"
	gem "compass", "1.0.0.alpha.20"
	gem "susy", "2.1.2"
	gem "breakpoint", "2.4.2"
	gem "oily_png"

end