name: Oliver Davies
description: Drupal Developer and Consultant
locale: en-GB

avatar:
    path: "/images/social-avatar.jpg"

drupalorg:
    name: opdavies
    url: 'https://www.drupal.org/u/%drupalorg.name%'

email: oliver@oliverdavies.uk

experience:
  start_year: 2007

github:
    gist:
        url: 'https://gist.github.com/%github.name%'
    name: opdavies
    url: 'https://github.com/%github.name%'

linkedin:
    name: opdavies
    url: 'https://www.linkedin.com/in/%linkedin.name%'

menus:
    footer:
        - title: About
          href: /
          is_active: '^//$'

        - title: Blog
          href: /blog
          is_active: '^/blog/?'

        - title: Talks
          href: /talks
          is_active: '^/talks/?'
        - title: Recommendations
          href: /recommendations

        - title: Daily list
          href: /daily
    main: []

packagist:
    name: opdavies
    url: 'https://packagist.org/packages/%packagist.name%'

plausible:
    domain: ~

savvycal:
    name: opdavies
    url: 'https://savvycal.com/%savvycal.name%'

speakerdeck:
    name: opdavies
    url: 'https://speakerdeck.com/%speakerdeck.name%'

twitter:
    name: opdavies
    url: 'https://twitter.com/%twitter.name%'

work:
    company:
        name: Transport for Wales
        url: https://tfw.wales
    role: Lead Software Developer

youtube:
    channel:
        id: UCkeK0qF9HHUPQH_fvn4ghqQ
        url: 'https://www.youtube.com/channel/%youtube.channel.id%'
