sculpin_content_types:
    daily_emails:
        permalink: archive/:year/:month/:day/:basename/
    pages:
        permalink: /:basename/
    posts:
        permalink: blog/:basename/
        taxonomies: [tags]
    projects:
        layout: default
        permalink: projects/:basename/
    talks:
        permalink: talks/:basename/

services:
    App\TwigExtension\TalkExtension:
        tags:
            - { name: twig.extension }
