name: Main

on:
  push:
    branches:
      - main

env:
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to the Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: make build-images
      - run: make push-images

# vim: sw=2 ts=2
