---
name: Test and Build

on:
  pull_request:

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: ./run ci:install

      - name: Run tests
        run: ./run ci:test

      - name: Generate the website
        run: |
          ./run ci:build
          tree output_prod
